services:

  api:
    build: .
    command: uvicorn session_13.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      DB_HOST: db
      DB_PORT: 5432
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

