start:
	poetry run python manage.py runserver

migrate:
	poetry run python manage.py migrate

migrations:
	poetry run python manage.py makemigrations $(app)

createsuperuser:
	poetry run python manage.py createsuperuser