# Generated by Django 5.1.7 on 2025-03-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_alter_uploadedfile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
            },
        ),
        migrations.AlterModelTable(
            name="uploadedfile",
            table="uploaded_files",
        ),
    ]
