# Generated by Django 5.1.7 on 2025-03-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_alter_uploadedfile_options_alter_uploadedfile_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={},
        ),
        migrations.AlterModelTable(
            name="uploadedfile",
            table=None,
        ),
    ]
