# Generated by Django 5.1.7 on 2025-03-28 15:11

import stats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to=stats.models.user_directory_path),
        ),
    ]
