# Generated by Django 5.1.7 on 2025-03-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0002_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(null=True, upload_to="tasks/"),
        ),
    ]
